### ISSUE TITLE
Re-scaling

### ISSUE THREAD

**Issue by l-welder** [FZJ-IEK3-VSA/tsam#17] opened 2018-07-09 14:30 UTC
Re-scaling affects extrem values of time series

**Comment by OriolRaventos** [comment] 2018-09-28 10:58
Just want to make precise the concrete issues with re-scaling I am finding out and an easy way to address it.

The fact that the added centers (containing the extreme values in one column) are not scaled happens with the “append” and the “new_cluster_center” conditions (although the rest of the centers do are scaled).

However with the “replace_center” is even stranger because just the columns of which we are taking the extreme values are substituted (instead of substituting the whole center). Hence we have columns that are scaled and columns that are not scaled. I believe that the intention of the "replace_center" is to replace the whole center. It can be easily changed.

What I do to overcome this issue is to do the clustering “unscaled” and then do the scaling myself afterwards. This could be easily implemented directly in the tsam package just changeing the place of the scaling.

**Comment by l-kotzur** [comment] 2019-06-14 15:21
Sorry for the late answer. 

@OriolRaventos 
Actually, this behavior of not rescaling the defined extreme periods is on purpose. If you want to include those into the optimization, it would be problematic if they would be downscaled or upscaled first. Therefore, they are excluded from the rescaling procedure.

@l-welder 
I am not able to reproduce this error. Nevertheless, I added some validation lines that test if the clustered time series stay in the max and min limits of the original time series, and raise a warning. 

I would close this issue but re-open it in case the problem occurs again.

**Comment by l-welder** [comment] 2019-06-17 13:43
@l-kotzur 
I send you an email with a snippet showing the problem occurs again (however this time with a warning (: ). Should we reopen the issue?

**Comment by maximilian-hoffmann** [comment] 2020-06-08 08:52
I would like the snippet as well, @l-kotzur . However, we've got a corresponding issue on GitLab where we will fix this before the next release. Therefore, I will close this issue. 😄

**Closed by maximilian-hoffmann** 2020-06-08 08:52 UTC
